config/routes.rb
Codebuddies::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:show, :index], :shallow => true do
    resources :postings
  end

  root 'static#start'
  match '/postings',                        to: 'postings#all',                   via: 'get'
  match '/remote_languages',                to: 'users#remote_languages_edit',    via: 'patch'
  match '/remote_languages',                to: 'users#remote_languages_delete',  via: 'delete'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)    
    user ||= User.new
    if user.admin?
        can :manage, :all
        can :access, :rails_admin
    end
    can [:read, :all], Posting
    can [:new, :create, :edit, :update, :destroy], Posting, :user_id => user.id
    can [:show, :index], User
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_and_belongs_to_many :postings, join_table: :postings_languages
end

app/models/posting.rb
class Posting < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :languages, presence: true
  validates_associated :user
  has_and_belongs_to_many :languages, join_table: :postings_languages

  self.per_page = 10

  default_scope { order('updated_at DESC') }

  def self.add_or_create_languages(selected, posting)
      #expected input is a string of languages, uniq makes sure there are no duplicate tags
      selected = selected.split(',').collect { |string| string.strip.downcase }
      selected.uniq!
      #if there are no params we skip this part and the validation takes care of the rest
      selected.each { |l| posting.languages << Language.find_or_create_by(title: l) } unless selected == nil
  end 

  def self.fuzzy_titles(title)
      self.where('title Like ?', "%#{title}%")
  end

  def self.postings_by_language(title)
      self.joins(:languages).where('languages.title' => title)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :postings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username


  # sets default pagiantion per page
  self.per_page = 5

  def admin?
    admin
  end

  def get_username
    "#{user.username}"
  end

  def self.find_user_postings(user_id)
    self.find(user_id).postings.order('updated_at DESC')
  end

  scope :find_username, -> search  { where('username Like ?', "%#{search}%") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters      
      devise_parameter_sanitizer.for(:account_update) do 
        |u| u.permit(:bitbucket, :about_me, :github, :username, :email,
                     :password, :password_confirmation, :current_password) 
      end

      devise_parameter_sanitizer.for(:sign_up) do
        |u| u.permit(:username, :email, :password, :password_confirmation)
      end
      
    end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :authenticate_user!, :except => :all
  load_and_authorize_resource :except => :create

  def index        
    @postings = User.find_user_postings(params[:user_id]).page(params[:page])
  end

  def new
    @languages = Language.all
  end

  def create
    @posting = current_user.postings.new(params.require(:posting).permit(:title, :description))
    Posting.add_or_create_languages(params[:posting_languages], @posting)
    create_save(DEFAULT_WARNING)
  end

  def all
    query = params[:search]
    query_tipe = params[:search_type]
    flash[:warning] = "Your search didn't match any results"
    
    if query_tipe == 'Title'
      @postings = @postings.fuzzy_titles(query)
    elsif query_tipe == 'Language'
      @postings = @postings.postings_by_language(query)
    end
    @postings = @postings.page(params[:page])    
  end

  def edit
    @known_languages = ''
    @posting.languages.each_with_index do |l, i|
      if i == 0
        @known_languages += l.title
      else
        @known_languages += ", #{l.title}"
      end
    end
  end

  def update
    @posting.update(title: params[:posting][:title], description: params[:posting][:description])
    @posting.languages.delete(:all)
    Posting.add_or_create_languages(params[:posting_languages], @posting)
    update_save(DEFAULT_WARNING)
  end

  def destroy
    #needs a redirect in case something goes wrong
    Posting.destroy(params[:id])
    redirect_to user_postings_path(current_user.id)
  end

  private

    DEFAULT_WARNING = "Please make sure you've filled all the fields!"

    def create_save(warning)
      if @posting.save
        redirect_to user_postings_path(current_user.id)
      else
        flash[:notice] = warning
        redirect_to new_user_posting_path(current_user.id)
      end
    end

    def update_save(warning)
      if @posting.save
        redirect_to user_postings_path(current_user.id)
      else
        flash[:notice] = warning
        redirect_to new_user_posting_path(params[:id])
      end

    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  protected

  #redirects user to edit profile after sign up,
  #:new_user => true is used to display a welcoming message
  def after_sign_up_path_for(resource)
    url_for(action: 'edit', controller: 'registrations', :params => {:new_user=>true})
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def start
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  load_and_authorize_resource
  def show
  end

  def index
    @users = User.find_username(params[:search]).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_nav.html.erb
<ul id="navigation" class="clearfix">
    <li id="nav_menu"><span>MENU</span></li>
    <li><%= link_to "Home", root_path %></li>
    <% if current_user %>
        <li> <%= link_to "Profile", edit_user_registration_path %> </li>
        <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>
        <li><%= link_to "New posting", new_user_posting_path(current_user) %></li>
        <li><%= link_to "My postings", user_postings_path(current_user) %></li>
        <% if current_user.admin? %>
            <li><%= link_to "Administration", rails_admin_path %></li>
        <% end %>
    <% else %>
        <li> <%= link_to "Sign in", new_user_session_path %> </li>
        <li><%= link_to "Register", new_user_registration_path %></li>
    <% end %>
    <li><%= link_to "Members", users_path %></li>
    <li><%= link_to "Postings", postings_path %></li>
    <li><%= link_to "About", '#' %> </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codebuddies</title>
  <meta name="viewport" content="initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render "layouts/nav" %>
    <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>

    <hr>
    <% if current_user %>
    <ul>
      <li><%= params.inspect %></li>
      <li><%= current_user.id %></li>
    </ul>
    <% end %>

</body>
</html>

app/views/postings/_postings.html.erb
<% if @postings.blank? %>
  <p><%= flash[:warning] %></p>
<% end %>

<div class="span_2_of_4  center">
  <% @postings.each do |post|%>
    <%= render "post", post: post %>
  <% end %>
  <%= will_paginate %>
</div><!-- span -->

app/views/postings/all.html.erb
<div class="section group">
  <div class="span_2_of_4 center">
    <%= form_tag postings_path, id: :postings_search, class: 'clearfix search', :method => 'get' do %>
            <%= text_field_tag :search, params[:search], placeholder: 'Search here', class: 'styled-input' %>
            <!-- outer div is needed for the select box to work properly -->
            <div class="styled-select">
              <%= select_tag :search_type, options_for_select([ "Title", "Language" ], params[:search_type]), class: 'cus'%>
            </div>
            <%= submit_tag "Search", class: 'styled-button' %>
    <% end %>
  </div>
  <%= render 'postings' %>
</div>

app/views/postings/edit.html.erb
<div class="section group half">
  <div class="col span_4_of_4">
      <h1>Edit your posting</h1>

      <%= form_for @posting, url: { action: "update" }, method: "patch" do |f| %>
        <div>
          <%= f.label :title %> <br>
          <%= f.text_field :title %>
        </div>

        <div>
          <%= f.label :description %><br>
          <%= f.text_area :description, size:"80x12" %>
        </div>

        <%# f.select :languages, @selected_collection, { include_hidden: false }, { multiple: :true } %>
        <div>
          <%= f.label :languages %><br>
          <%= text_field_tag :posting_languages, @known_languages %>
        </div>

        <%= f.submit "Update posting" %>
      <% end %>

  </div>
</div>

app/views/postings/index.html.erb
<div class="section group">
  <%= render 'postings' %>
</div>

app/views/postings/new.html.erb
<div class="section group half">
  <div class="col span_4_of_4">
      <h1>Create a new posting</h1>

      <%= form_for @posting, url: { action: "create" } do |f| %>
        <div>
          <%= f.label :title %> <br>
          <%= f.text_field :title %>
        </div>

        <div>
          <%= f.label :description %><br>
          <%= f.text_area :description, size:"80x12" %>
        </div>

        <div>
          <%= f.label :languages %><br>
          <%= text_field_tag :posting_languages %>
        </div>

        <%= f.submit "New posting" %>
      <% end %>

  </div>
</div>

app/views/users/_user.html.erb
<div class="col span_4_of_4">
    <h1><%= user.username %></h1>
    <hr>
    <p>Github:</p>
    <p><%= user.github %></p><br>
    <p>Bitbucket:</p>
    <p><%= user.bitbucket %></p><br>
    <p>About me:</p>
    <p><%= user.about_me %></p><br>

    <%= link_to "Postings", user_postings_path(user.id) %>
</div>

app/views/users/_users.html.erb
<div id="users_container">
    <% @users.each do |user| %>
      <%= render "user", user: user %>
    <% end %>

    <%= will_paginate %>
</div>

app/views/users/index.html.erb
<div class="users section group">

  <%= form_tag users_path, id: :user_search, :method => 'get' do %>
      <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search" %>
      </p>
  <% end %>

  <%= render "users" %>

</div>

app/views/users/show.html.erb
<%= render "user", user: @user %>